version: "3.1"

# networks:
#   lamp_net:

services:
  server:
    image: php:8.0-apache
    container_name: apache
    command: "/bin/sh -c 'docker-php-ext-install mysqli && a2enmod headers && a2enmod rewrite && exec apache2-foreground'"
    restart: always
    environment:
      TZ: America/New_York
      MODE: development
    volumes:
      - ./www:/var/www/html/:rw
    ports:
      - 80:80
  # server:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: '${APP_NAME}-server'
  #   ports:
  #     - '${APP_PORT}:80'
  #   working_dir: /var/www/html
  #   environment:
  #     - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}?serverVersion=10.5'
  #   volumes:
  #     - ./www:/var/www/html
  #     - ./apache/sites-enabled:/etc/apache2/sites-enabled
  #     - ./php/extra-php-config.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    # depends_on:
    #   mariadb:
    #     condition: service_healthy
    # networks:
    #   - lamp_net

  mariadb:
    image: mariadb:10.7.1
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    # volumes:
    #   - ./mariadb/data:/var/lib/mysql:rw
      # - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    # healthcheck:
    #   test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
    #   interval: 5s
    #   retries: 5
    # networks:
    #   - lamp_net

  phpmyadmin:
    image: phpmyadmin:5.1.1
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb